### ISSUE TITLE
engagement create template not rendering properly in production server

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#10]
The engagement template is quite lengthy and has lots of multiple choice (manytomany) fields to complete. I had mocked up a working template using` django-multiselectfield` and `django-easy-select2` in development, but this is not working as intended when deployed.

**Comment by banillie** [comment]
This could be because I didn't upload static files in production. The third party package I'm using is easy_select2.

**Comment by banillie** [comment]
It was because I hadn't uploaded static files to production.

**Comment by banillie** [comment]
Re-opening this issue as static files are no longer loading properly. 

It would appear this has been a re-issue since I push up the `.github/workflows` directory and files, which then triggers the `CI/CD Django, Postgres, DigitalOcean` workflow. This workflow starts a new deployment via `.do/.app.yaml`. This workflow is working and the deployment is successful. 

However, the apps statics files are no longer loading into production? I'm not sure what's causing this. It could be related to the above changes, but it is not obvious to me if/how the two are related. 

I have successfully loaded the static files into the `spaces` section of my DO account. When I run `python manage.py collectstatic' the apps static files are uploaded successfully. 

I have also tried deploying the app directly from the DO. I used this route the first time I put static files into production. However, this no longer works. 

@yulqen any suggestions and advice on the above would be gratefully received. Maybe something to discuss on Friday?

**Comment by yulqen** [comment]
I've not heard of the CI service you're using but will dig in on Friday. 👍🏻

**Comment by banillie** [comment]
@yulqen sorted. I had to update the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY values in the env variables in the do console. Not sure how they ended up being different! The css are now render again :balloon: 

From what I can see the values for these keys are encrypted in the .do app.yaml file. 

Thank you for helping me :+1:
