### ISSUE TITLE
Raised by team

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#19]
- Governance change to tier **DONE**
- Change engagement type to engagement topic as per Caroline's comments in November **DONE**
- In Stakeholder create/update drop down option for group **DONE**
- Categories the display of engagements by Years then Months. **SEPARATE ISSUES CREATED** 
- Add Group option to projects. **DONE**
- change abbreviation to project abbreviation **DISCUSS FURTHER**
- change stage name to business case. **DONE**
- make changes to project, stakeholder, ppdds pages with Mo's text. **DONE**

**Comment by clgoodman** [comment]
Hi Will,

CDG doesn't appear as a DfT Group could you add this to the list please?

**Comment by clgoodman** [comment]
Also, it doesn't let me save a project unless there is an abbreviation. Says this field is required.

**Comment by banillie** [comment]
@clgoodman yes at the moment there is a requirement for an acronym to be provided. I think its good practice to have both. But, I can make it optional if necessary.

**Comment by clgoodman** [comment]
On Home page "various themes **that's** we engage with colleagues' 
need to remove the 's from that

**Comment by banillie** [comment]
Actions completed. Closing.
