### ISSUE TITLE
Create a development and production settings file

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#22]
Things that need to happen:
- automatically switch off debug in production / on debug in development.

**Comment by banillie** [comment]
Completed. Now have two setting files. settings and settings_local. 
settings_local is run via `python manage.py runserver --settings=project_tracker.settings_local`

**Comment by banillie** [comment]
@yulqen in relation to the above should I set up a alias for the `python manage.py runserver --settings=project_tracker.settings_local` command or is there another/better way of doing this? I think you mentioned to me another method of running common commands via a particular file but can't remember the name.

**Comment by yulqen** [comment]
Make. We'll discuss later.

**Comment by banillie** [comment]
Cool. See you at 15.15
