### ISSUE TITLE
Change URL/ IP Address to PPDD Engagement Tracker

### ISSUE THREAD

**Issue by clgoodman** [banillie/project_tracker#25]
Hi Will, 

As discussed, the website address is hard to remember, can this be changed to PPDD Engagement Tracker to make it easier for users to remember?

**Comment by banillie** [comment]
@clgoodman I have sent an email to you and Mo. Awaiting your response. Closing this issue for now as I believe Mo felt that a domain name might not be required at this time. Keep on tracking :haha:
