### ISSUE TITLE
Download in deployment

### ISSUE THREAD

**Issue by banillie** [banillie/project_tracker#39]
Download error in production. Relevant helpful guidance here. 

- https://stackoverflow.com/questions/65209779/gcp-app-engine-oserror-errno-30-read-only-file-system
- https://cloud.google.com/appengine/docs/standard/python3/using-temp-files

**Comment by banillie** [comment]
`project_tracker\pages\views` is now. 

'''
def download_master(request):
    today = datetime.date.today()
    file_name = f"engagement_tracker_master_{today}.xlsx"
    with tempfile.TemporaryDirectory() as tmpdir:
        save_path = os.path.join(tmpdir, file_name)
        excel_download(save_path)
        with open(save_path, "rb") as excel:
            data = excel.read()
            response = HttpResponse(data, content_type="application/vnd.ms-excel")  # what's content type
            response["Content-Disposition"] = f"attachment; filename={file_name}"
            return response
'''

This works in deployment environment. @yulqen what do you think? Is using a tmp directory in this way ok/appropriate?

**Comment by yulqen** [comment]
No problem using temp directories full stop. A good idea - that's what they're for. Probably won't work for GCP as discussed last week - you probably needs to sort out some sort of bucket for these files.

**Comment by banillie** [comment]
Great. It does work in GCP. So all good! 🐍
